<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Bancos.aspx.cs" Inherits="PRESENTACION.AdministradorBancos" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <link rel="stylesheet"  href="Estilos/contenedores.css"/>
    <link rel="stylesheet"  href="Estilos/estiloMenu.css"/>
</head>
<body>
    <div id="top">
        Usted esta conectado como
        <asp:Label ID="lblUsuario" runat="server"></asp:Label>
    </div>
    <form id="form1" runat="server">
        <div class="contenedor">
            <div class="links">
                -<asp:LinkButton ID="linkNuevoBanco" runat="server" OnClick="linkNuevoBanco_Click">Nuevo Banco</asp:LinkButton>
                <br />
                -<asp:LinkButton ID="linkBuscar" runat="server" OnClick="linkBuscar_Click">Buscar</asp:LinkButton>
                <br />
                -<asp:LinkButton ID="linkVolver" runat="server" OnClick="linkVolver_Click">Volver</asp:LinkButton>
            </div>

            <div class="gridview">
                <asp:GridView ID="grdBancos" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="CodBanco" DataSourceID="SqlBancos">
                    <Columns>
                        <asp:BoundField DataField="CodBanco" HeaderText="CodBanco" ReadOnly="True" SortExpression="CodBanco" />
                        <asp:BoundField DataField="NombreBanco" HeaderText="NombreBanco" SortExpression="NombreBanco" />
                    </Columns>
                </asp:GridView>
                <asp:SqlDataSource ID="SqlBancos" runat="server" ConnectionString="<%$ ConnectionStrings:ZapateriaConnectionString %>" SelectCommand="SELECT * FROM [Bancos] ORDER BY [CodBanco]" DeleteCommand="DELETE FROM [Bancos] WHERE [CodBanco] = @CodBanco" InsertCommand="INSERT INTO [Bancos] ([CodBanco], [NombreBanco]) VALUES (@CodBanco, @NombreBanco)" UpdateCommand="UPDATE [Bancos] SET [NombreBanco] = @NombreBanco WHERE [CodBanco] = @CodBanco">
                    <DeleteParameters>
                        <asp:Parameter Name="CodBanco" Type="Int32" />
                    </DeleteParameters>
                    <InsertParameters>
                        <asp:Parameter Name="CodBanco" Type="Int32" />
                        <asp:Parameter Name="NombreBanco" Type="String" />
                    </InsertParameters>
                    <UpdateParameters>
                        <asp:Parameter Name="NombreBanco" Type="String" />
                        <asp:Parameter Name="CodBanco" Type="Int32" />
                    </UpdateParameters>
                </asp:SqlDataSource>
            </div>
            
        </div>
    </form>
</body>
</html>
