<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Categorias.aspx.cs" Inherits="PRESENTACION.AdministradorCategorias" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <link rel="stylesheet"  href="Estilos/contenedores.css"/>
    <link rel="stylesheet"  href="Estilos/estiloMenu.css"/>
</head>
<body>
    <div id="top">
        Usted esta conectado como
        <asp:Label ID="lblUsuario" runat="server"></asp:Label>
    </div>
    <form id="form1" runat="server">
        <div class="contenedor">
            <div class="links">
                -<asp:LinkButton ID="linkNuevaCategoria" runat="server" OnClick="linkNuevaCategoria_Click">Nueva Categoria</asp:LinkButton>
                <br />
                -<asp:LinkButton ID="linkBuscar" runat="server" OnClick="linkBuscar_Click">Buscar</asp:LinkButton>
                <br />
                -<asp:LinkButton ID="linkVolver" runat="server" OnClick="linkVolver_Click">Volver</asp:LinkButton>
            </div>
            
            <div class="gridview">
                <asp:GridView ID="grdCategorias" runat="server" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="CodCategoria" DataSourceID="SqlCategoria">
                    <Columns>
                        <asp:BoundField DataField="CodCategoria" HeaderText="CodCategoria" SortExpression="CodCategoria" ReadOnly="True" />
                        <asp:BoundField DataField="NombreCategoria" HeaderText="NombreCategoria" SortExpression="NombreCategoria" />
                    </Columns>
                </asp:GridView>
                <asp:SqlDataSource ID="SqlCategoria" runat="server" ConnectionString="<%$ ConnectionStrings:ZapateriaConnectionString %>" SelectCommand="SELECT * FROM [Categorias] ORDER BY [CodCategoria]" DeleteCommand="DELETE FROM [Categorias] WHERE [CodCategoria] = @CodCategoria" InsertCommand="INSERT INTO [Categorias] ([CodCategoria], [NombreCategoria]) VALUES (@CodCategoria, @NombreCategoria)" UpdateCommand="UPDATE [Categorias] SET [NombreCategoria] = @NombreCategoria WHERE [CodCategoria] = @CodCategoria">
                    <DeleteParameters>
                        <asp:Parameter Name="CodCategoria" Type="Int32" />
                    </DeleteParameters>
                    <InsertParameters>
                        <asp:Parameter Name="CodCategoria" Type="Int32" />
                        <asp:Parameter Name="NombreCategoria" Type="String" />
                    </InsertParameters>
                    <UpdateParameters>
                        <asp:Parameter Name="NombreCategoria" Type="String" />
                        <asp:Parameter Name="CodCategoria" Type="Int32" />
                    </UpdateParameters>
                </asp:SqlDataSource>
            </div> 
        </div>
    </form>
</body>
</html>
