<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Proveedores.aspx.cs" Inherits="PRESENTACION.AdministradorProveedores" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <link rel="stylesheet"  href="Estilos/contenedores.css"/>
    <link rel="stylesheet"  href="Estilos/estiloMenu.css"/>
</head>
<body>
    <div id="top">
        Usted esta conectado como
        <asp:Label ID="lblUsuario" runat="server"></asp:Label>
    </div>
    <form id="form1" runat="server">
        <div class="contenedor">
            <div class="links">
                -<asp:LinkButton ID="linkNuevoProveedor" runat="server" OnClick="linkNuevoProveedor_Click">Nuevo Proveedor</asp:LinkButton>
                <br />
                -<asp:LinkButton ID="linkBuscar" runat="server" OnClick="linkBuscar_Click">Buscar</asp:LinkButton>
                <br />
                -<asp:LinkButton ID="linkVolver" runat="server" OnClick="linkVolver_Click">Volver</asp:LinkButton>
            </div>
            
            <div class="gridview">
                <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="CodProveedor" DataSourceID="SqlProveedor">
                    <Columns>
                        <asp:BoundField DataField="CodProveedor" HeaderText="CodProveedor" SortExpression="CodProveedor" ReadOnly="True" />
                        <asp:BoundField DataField="NombreProveedor" HeaderText="NombreProveedor" SortExpression="NombreProveedor" />
                        <asp:BoundField DataField="CUIL" HeaderText="CUIL" SortExpression="CUIL" />
                        <asp:BoundField DataField="RazonSocial" HeaderText="RazonSocial" SortExpression="RazonSocial" />
                    </Columns>
                </asp:GridView>
                <asp:SqlDataSource ID="SqlProveedor" runat="server" ConnectionString="<%$ ConnectionStrings:ZapateriaConnectionString %>" SelectCommand="SELECT * FROM [Proveedores] ORDER BY [CodProveedor]" DeleteCommand="DELETE FROM [Proveedores] WHERE [CodProveedor] = @CodProveedor" InsertCommand="INSERT INTO [Proveedores] ([CodProveedor], [NombreProveedor], [CUIL], [RazonSocial]) VALUES (@CodProveedor, @NombreProveedor, @CUIL, @RazonSocial)" UpdateCommand="UPDATE [Proveedores] SET [NombreProveedor] = @NombreProveedor, [CUIL] = @CUIL, [RazonSocial] = @RazonSocial WHERE [CodProveedor] = @CodProveedor">
                    <DeleteParameters>
                        <asp:Parameter Name="CodProveedor" Type="String" />
                    </DeleteParameters>
                    <InsertParameters>
                        <asp:Parameter Name="CodProveedor" Type="String" />
                        <asp:Parameter Name="NombreProveedor" Type="String" />
                        <asp:Parameter Name="CUIL" Type="String" />
                        <asp:Parameter Name="RazonSocial" Type="String" />
                    </InsertParameters>
                    <UpdateParameters>
                        <asp:Parameter Name="NombreProveedor" Type="String" />
                        <asp:Parameter Name="CUIL" Type="String" />
                        <asp:Parameter Name="RazonSocial" Type="String" />
                        <asp:Parameter Name="CodProveedor" Type="String" />
                    </UpdateParameters>
                </asp:SqlDataSource>
            </div>
        </div>
    </form>
</body>
</html>
