<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Usuarios.aspx.cs" Inherits="PRESENTACION.AdministradorUsuarios" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <link rel="stylesheet"  href="Estilos/contenedores.css"/>
    <link rel="stylesheet"  href="Estilos/estiloMenu.css"/>
</head>
<body>
    <div id="top">
        Usted esta conectado como
        <asp:Label ID="lblUsuario" runat="server"></asp:Label>
    </div>
    <form id="form1" runat="server">
        <div class="contenedor">
            <div class="links">
                -<asp:LinkButton ID="linkBuscar" runat="server" OnClick="linkBuscar_Click">Buscar</asp:LinkButton>
                <br />
                -<asp:LinkButton ID="linkVolver" runat="server" OnClick="linkVolver_Click">Volver</asp:LinkButton>
            </div>
            
            <div class="gridview">
                <asp:GridView ID="gViewUsuarios" runat="server" AutoGenerateColumns="False" DataKeyNames="Email" DataSourceID="SqlUsuarios" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowDeleting="gViewUsuarios_RowDeleting" OnRowUpdated="gViewUsuarios_RowUpdated">
                    <Columns>
                        <asp:BoundField DataField="Email" HeaderText="Email" ReadOnly="True" SortExpression="Email" />
                        <asp:BoundField DataField="Clave" HeaderText="Clave" SortExpression="Clave" />
                        <asp:BoundField DataField="CodCliente" HeaderText="CodCliente" SortExpression="CodCliente" />
                        <asp:CheckBoxField DataField="TipoUsuario" HeaderText="TipoUsuario" SortExpression="TipoUsuario" />
                    </Columns>
                </asp:GridView>
                <asp:SqlDataSource ID="SqlUsuarios" runat="server" ConnectionString="<%$ ConnectionStrings:ZapateriaConnectionString %>" SelectCommand="SELECT * FROM [Usuarios] ORDER BY [CodCliente]" DeleteCommand="DELETE FROM [Usuarios] WHERE [Email] = @Email" InsertCommand="INSERT INTO [Usuarios] ([Email], [Clave], [CodCliente], [TipoUsuario]) VALUES (@Email, @Clave, @CodCliente, @TipoUsuario)" UpdateCommand="UPDATE [Usuarios] SET [Clave] = @Clave, [CodCliente] = @CodCliente, [TipoUsuario] = @TipoUsuario WHERE [Email] = @Email">
                    <DeleteParameters>
                        <asp:Parameter Name="Email" Type="String" />
                    </DeleteParameters>
                    <InsertParameters>
                        <asp:Parameter Name="Email" Type="String" />
                        <asp:Parameter Name="Clave" Type="String" />
                        <asp:Parameter Name="CodCliente" Type="Int32" />
                        <asp:Parameter Name="TipoUsuario" Type="Boolean" />
                    </InsertParameters>
                    <UpdateParameters>
                        <asp:Parameter Name="Clave" Type="String" />
                        <asp:Parameter Name="CodCliente" Type="Int32" />
                        <asp:Parameter Name="TipoUsuario" Type="Boolean" />
                        <asp:Parameter Name="Email" Type="String" />
                    </UpdateParameters>
                </asp:SqlDataSource>
            </div>
        </div>
    </form>
</body>
</html>
